export const VFX_TECHNIQUE_LIBRARY = {
    camera: [
      { name: "Dolly Zoom (Vertigo)", desc: "Counter-zoom while dollying, surreal scale shift", source: "wikipedia.org/wiki/Dolly_zoom" },
      { name: "Crash Zoom", desc: "Rapid hard zoom-in punctuating moment" },
      { name: "Whip Pan", desc: "Fast lateral pan with motion blur (often cliché)" },
      { name: "Pass-Through", desc: "Camera physically moves through object/person", source: "eyecannndy.com/technique/pass-through" },
      { name: "Snorricam Mount", desc: "Rig fixed to subject, background moves around them" },
      { name: "Crane Reveal", desc: "Vertical crane move revealing new context" },
      { name: "Parallax", desc: "Foreground/background shift at different rates revealing depth", source: "eyecannndy.com/technique/parallax" },
      { name: "Push-In", desc: "Slow forward dolly to subject, builds intimacy" },
      { name: "Pull-Out (Reverse Dolly)", desc: "Backward dolly revealing surrounding context" },
      { name: "Arc Shot", desc: "Camera curves around subject on radius" },
      { name: "Orbit", desc: "Full 360 around static subject" },
      { name: "POV Shot", desc: "First-person from character's perspective" },
      { name: "Object POV", desc: "Camera as object's viewpoint (mirror, gun, etc.)", source: "eyecannndy.com/technique/as-object" },
      { name: "Rack Focus", desc: "Focus shifts between foreground/background mid-shot" },
      { name: "Split Diopter", desc: "Two focal planes sharp at once via split lens" },
      { name: "Tilt", desc: "Vertical pivot of camera body" },
      { name: "Camera Roll", desc: "Camera rotation rolls scene into next" },
      { name: "Anamorphic Squeeze", desc: "Horizontal stretch/compress lens distortion" },
      { name: "Rotational Match", desc: "Both shots rotate at matched speed bridging cut" },
      { name: "Bird's Eye / Aerial", desc: "Overhead vertical-down framing or drone-altitude wide" },
      { name: "Worm's Eye / Ground Level", desc: "Extreme low angle looking up from floor" },
      { name: "Periscope Rise", desc: "Camera rises vertically revealing scene above" },
      { name: "Mirror Flip", desc: "Frame flips horizontally as if mirrored, reveals B" },
      { name: "Lock-On", desc: "Frame locked to subject, world rotates around them" },
      { name: "Tracking Shot", desc: "Lateral movement parallel to subject" },
      { name: "Steadicam Float", desc: "Smooth gliding follow regardless of operator gait" },
      { name: "Handheld Verite", desc: "Naturalistic shake conveys realism/urgency" },
      { name: "Probe Lens Macro", desc: "Tiny lens enters extreme close detail" },
      { name: "Top-Down Reveal", desc: "Bird's eye descends into eye-level shot" },
      { name: "Match-Frame Cut", desc: "Same composition framing carries across cut" },
      { name: "Dutch Angle", desc: "Tilted horizon, unease/instability feeling" },
      { name: "Fisheye", desc: "Ultra-wide spherical lens distortion, fish-bowl framing" },
      { name: "FPV Drone", desc: "First-person drone flight, immersive racing-style motion" },
      { name: "Bolt Cam", desc: "Motion-control rig for precise repeatable moves" },
      { name: "Fixed Cam", desc: "Locked-off static frame, no camera motion at all" },
      { name: "Central Framing", desc: "Subject dead-center, Wes Anderson symmetry" },
      { name: "Double Dolly", desc: "Two simultaneous dollies in opposite directions" },
      { name: "Conveyor", desc: "Camera moves laterally as if on conveyor belt" },
      { name: "Boomerang", desc: "Movement out and reversed back to start point" },
      { name: "Falling", desc: "Camera falls with subject, vertical drop perspective" },
      { name: "Omnidirectional", desc: "360° camera capturing full sphere, VR-style", source: "eyecannndy.com/technique/omnidirectional" },
      { name: "Slit-Scan", desc: "Single row of pixels exposed over time, smeared distortion" },
      { name: "Forced Perspective", desc: "Composition makes object appear larger/smaller than real" },
      { name: "Hyperbolic Dolly", desc: "Curved dolly path bending around subject" },
      { name: "Crab Walk", desc: "Sideways tracking matching subject's gait" },
      { name: "Subject-Lock Pan", desc: "Camera pans to keep subject pinned in frame" },
      { name: "Vertical Pan", desc: "Up-or-down pan motion as reveal device" },
      { name: "Drone Tail", desc: "Drone follows subject from behind through space" },
      { name: "Float Through", desc: "Slow drifting forward, dreamlike weightless" },
      { name: "Reverse Tracking", desc: "Subject walks toward camera that retreats" },
      { name: "Tiny Planet", desc: "360° image projected as small spherical world", source: "eyecannndy.com/technique/tiny-planet" },
      { name: "Diorama", desc: "Tilt-shift miniature look, real becomes toy-scale" },
      { name: "Bullet Cam", desc: "Macro-tracked POV from projectile's view" },
      { name: "Choreographed Camera", desc: "Camera move part of dance choreography itself" },
      { name: "Architexture", desc: "Architecture as primary visual subject, geometric reveal" }
    ],
    visual: [
      { name: "Match Dissolve", desc: "Cross-fade aligned on shape/color across both frames" },
      { name: "Cross Dissolve", desc: "Smooth opacity blend between two clips" },
      { name: "Light Bloom Bridge", desc: "Highlight overexposes to white, reveals new scene" },
      { name: "Lens Flare Wipe", desc: "Anamorphic streak sweeps across, hides cut" },
      { name: "Light Flash", desc: "White flash burst covers cut moment", source: "eyecannndy.com/technique/light-flash" },
      { name: "Color Wipe", desc: "Single color floods frame as transition wipe" },
      { name: "Liquid Morph", desc: "Subject melts/flows into next form organically" },
      { name: "Ink Bleed", desc: "Ink spreads across frame like dropped on paper" },
      { name: "Gel Dissolve", desc: "Translucent color gel passes over to swap scenes" },
      { name: "Refraction Shift", desc: "View bends through glass/water, refocuses on new scene" },
      { name: "Heat Haze Wipe", desc: "Air distortion ripples, image reforms behind" },
      { name: "Vapor Trail Reveal", desc: "Mist/smoke clears to expose end frame" },
      { name: "Smoke Curtain", desc: "Smoke fills frame, parts to reveal scene 2" },
      { name: "Light Streak Wipe", desc: "Streaking light bar sweeps across causing transition" },
      { name: "Bokeh Pull", desc: "Out-of-focus orbs pull aside revealing sharp scene" },
      { name: "Grain Storm", desc: "Heavy film grain builds, dissolves into next shot" },
      { name: "VHS Tracking Roll", desc: "Magnetic-tape rolling artifact swaps frames" },
      { name: "Datamosh", desc: "Compression artifacts smear A's motion onto B" },
      { name: "Color Cascade", desc: "Hue rolls through palette ending on scene 2 grade" },
      { name: "Color Shift", desc: "Palette swaps dramatically signaling tone change" },
      { name: "Holographic Shimmer", desc: "Iridescent prism light wash bridges shots" },
      { name: "Prismatic Reveal", desc: "Spectrum split clears revealing new frame" },
      { name: "Film Burn", desc: "Frame burns away from edge exposing next" },
      { name: "Strobe Cut", desc: "Rapid black flashes cover the cut" },
      { name: "Iris Wipe", desc: "Circular aperture closes/opens to swap scenes" },
      { name: "Shadow Pass", desc: "Shadow sweeps across frame revealing new scene" },
      { name: "Gradient Wipe", desc: "Soft gradient mask sweeps from one side" },
      { name: "Masking Reveal", desc: "Mask isolates region, fills with new footage", source: "eyecannndy.com/technique/masking" },
      { name: "Double Exposure", desc: "Two images overlay creating dreamlike merge" },
      { name: "Mixed Media", desc: "Live action + animation/illustration combined", source: "eyecannndy.com/technique/mixed-media" },
      { name: "Projections", desc: "Image projected onto surface within the scene", source: "eyecannndy.com/technique/projections" },
      { name: "Distortions", desc: "Geometric warping bends image into new shape" },
      { name: "Cinemagraph", desc: "Mostly still frame with one isolated moving element" },
      { name: "Collage", desc: "Multiple frames layered into single composition" },
      { name: "Duplication", desc: "Subject cloned multiple times across frame" },
      { name: "Feedback Loop", desc: "Frame recurses into itself infinitely" },
      { name: "Echo Print", desc: "Trailing duplicate ghosts behind moving subject" },
      { name: "Floating UI", desc: "Graphic elements float in 3D space within shot" },
      { name: "Fourth Wall Break", desc: "Subject acknowledges camera/viewer directly" },
      { name: "Glitch Tear", desc: "Digital tearing artifact rips across image" },
      { name: "Chromatic Aberration", desc: "RGB channels split offsetting edges" },
      { name: "Pixelation", desc: "Image breaks into large pixel blocks" },
      { name: "Tiled Repeat", desc: "Frame tiles into grid pattern" },
      { name: "Kaleidoscope", desc: "Mirrored radial multiplication of image" },
      { name: "Phantom Glow", desc: "Soft inner glow on key subjects" },
      { name: "Underwater Caustic", desc: "Water-light patterns rippling across surface" },
      { name: "Light Painting", desc: "Long exposure trails of moving light source" },
      { name: "Long Exposure Trail", desc: "Streaks of motion blur from extended shutter" },
      { name: "Halation Bloom Wipe", desc: "Warm red bloom expands and bridges cut" },
      { name: "Particle Disintegration", desc: "Subject crumbles into particles forming next scene" },
      { name: "Generative Pattern", desc: "Procedural algorithmic visuals bridging shots" }
    ],
    narrative: [
      { name: "Match Cut", desc: "Cut on shape/motion/color visual rhyme between scenes" },
      { name: "Smash Cut", desc: "Hard abrupt cut to contrasting tone/scene" },
      { name: "J-Cut", desc: "Audio of next scene starts before its picture" },
      { name: "L-Cut", desc: "Audio of previous scene continues into next picture" },
      { name: "Cross-Cut / Parallel Action", desc: "Alternating between two simultaneous actions" },
      { name: "Jump Cut", desc: "Same subject, time-skip via near-identical framing" },
      { name: "Kuleshov Effect", desc: "Meaning created by juxtaposition of two shots" },
      { name: "Reveal Twist", desc: "Final frame recontextualizes everything before" },
      { name: "Time Loop", desc: "End connects back to beginning, infinite reading" },
      { name: "Cause-Effect Cut", desc: "Action in A causes visible result in B" },
      { name: "Freeze-to-Action", desc: "Hold frame, then unfreeze into motion" },
      { name: "Prop Handoff", desc: "Object passes from A to B carrying continuity" },
      { name: "Object Morph", desc: "One object purposefully transforms into another" },
      { name: "Mirror Reflection Bridge", desc: "Cut at moment of mirror reflection swapping reality" },
      { name: "Doorway Portal", desc: "Walking through door = scene change motivation" },
      { name: "Photograph-Becomes-Real", desc: "Still image animates, viewer enters it" },
      { name: "Dream-to-Reality Slip", desc: "Subtle drift from dream state into waking world" },
      { name: "Before-After Wipe", desc: "Single subject shown before/after via vertical wipe" },
      { name: "Action Match", desc: "Cut on physical motion continuing across shots" },
      { name: "Whip-to-Reveal", desc: "Whip pan ends on a narratively meaningful subject" },
      { name: "Anthropo Reveal", desc: "Inanimate object presented as if it has soul/life" },
      { name: "Epiphany Beat", desc: "Hold moment of character realization before cut" },
      { name: "Cut-in Insert", desc: "Detail close-up inserted into wider scene" },
      { name: "Match on Sound", desc: "Cut bridged by sonic rhyme (door slam → drum)" },
      { name: "Memory Bridge", desc: "Object triggers cut to memory scene" },
      { name: "Object Lineage", desc: "Same object travels through multiple eras" },
      { name: "Camera Handoff", desc: "Camera follows new subject mid-shot" },
      { name: "Subject Switch", desc: "Frame attention transfers from A to B mid-shot" },
      { name: "Witness POV", desc: "Cut to bystander's viewpoint as device" },
      { name: "Hand-as-Bridge", desc: "Hand reaches into frame motivating cut" },
      { name: "Reverse Reveal", desc: "Camera retreats progressively expanding context" },
      { name: "Falling Bridge", desc: "Subject falls into new scene" },
      { name: "Anti-Climax Cut", desc: "Buildup cut to deliberately mundane reveal" },
      { name: "Flashforward", desc: "Brief cut to future moment then return" },
      { name: "Smash-and-Hold", desc: "Cut to image and hold long enough to imply meaning" }
    ],
    energy: [
      { name: "Speed Ramp", desc: "Tempo shifts from slow to fast or reverse mid-shot" },
      { name: "Freeze Frame Snap", desc: "Sudden hold on key beat then resumes" },
      { name: "Kinetic Typography", desc: "Text bursts onto frame in time with cut" },
      { name: "Beat-Locked Cut", desc: "Edit aligned exactly with music beat" },
      { name: "Stutter-Stop", desc: "Repeated micro-cuts create staccato rhythm" },
      { name: "Accelerated Montage", desc: "Cuts compress shorter and shorter" },
      { name: "Time-Stretch Hold", desc: "Long held frame followed by snap to next" },
      { name: "Bullet Time", desc: "Subject frozen while camera moves around them" },
      { name: "Step Print", desc: "Frames repeat creating juddery look" },
      { name: "Strobe Sync", desc: "Pulses of black/white sync to beat" },
      { name: "Multi-Cut Compression", desc: "Many micro-shots compressed into a beat" },
      { name: "Pulse-on-Bass", desc: "Frame scales subtly with each bass hit" },
      { name: "Drop-on-Beat Reveal", desc: "Reveal lands exactly on music drop" },
      { name: "Rhythmic Flash", desc: "White frames flash in rhythm pattern" },
      { name: "Slo-mo Glory", desc: "Significant moment held in extreme slow motion" },
      { name: "Hyperlapse", desc: "Massively sped-up motion through space", source: "eyecannndy.com/technique/hyperlapse" },
      { name: "Stop Motion", desc: "Frame-by-frame animation feel" },
      { name: "Time-Slice", desc: "Multiple cameras around subject create frozen pan" },
      { name: "Frame-Hold-Burst", desc: "Single frame held, bursts into rapid sequence" },
      { name: "Tempo Cut", desc: "Cut tempo accelerates then resolves" },
      { name: "Timelapse", desc: "Frame rate stretched, time speeds up visibly", source: "eyecannndy.com/technique/timelapse" },
      { name: "Reverse Motion", desc: "Action plays backward as effect" },
      { name: "Undercrank", desc: "Lower frame rate during capture, fast playback" },
      { name: "Overcrank", desc: "Higher frame rate, smooth slow motion" },
      { name: "Ramp-to-Freeze", desc: "Speed slows progressively into still" },
      { name: "Echo Beat", desc: "Each beat triggers repeated visual echo" },
      { name: "Tilt-on-Beat", desc: "Camera tilts in sync with rhythm" },
      { name: "Quick Zoom Burst", desc: "Multiple sharp zooms on rapid beats" },
      { name: "Snap Zoom", desc: "Single rapid zoom punctuating moment" },
      { name: "Frame Stutter", desc: "Rapid forward-back frame skipping" },
      { name: "Cascading Cuts", desc: "Series of cuts cascading in succession" },
      { name: "Tempo Drop", desc: "Sudden shift from high to low tempo" },
      { name: "Subdivision Cut", desc: "Cut on 16th or 32nd note subdivision" },
      { name: "Visual BPM Pulse", desc: "Whole frame pulses with BPM rhythm" },
      { name: "Build-Drop Reveal", desc: "Tension builds, reveal drops on key beat" }
    ],
    subtle: [
      { name: "Micro-Zoom", desc: "1.02x slow zoom, barely perceptible push" },
      { name: "Light Leak", desc: "Organic streak of warm light bleeds into frame" },
      { name: "Breathing Parallax", desc: "Layers shift with subject breath rhythm" },
      { name: "Optical Flow Morph", desc: "AI-driven smooth pixel flow between frames" },
      { name: "Dust Mote Drift", desc: "Particles drift in atmospheric backlight" },
      { name: "Lens Breathing", desc: "Subtle focal length shift during shot" },
      { name: "Exposure Pulse", desc: "Brightness rises and falls organically" },
      { name: "Fabric-Fold Reveal", desc: "Cloth folds in/out exposing new scene" },
      { name: "Paper-Turn", desc: "Image curls like turning page, reveals next" },
      { name: "Water-Surface Ripple", desc: "Liquid surface ripples and reforms scene" },
      { name: "Shadow-Pass Wipe", desc: "Soft shadow sweeps across, scene 2 emerges" },
      { name: "Cloud-Shadow Drift", desc: "Sky shadow passes over landscape, time shift" },
      { name: "Iris Bloom", desc: "Soft circular brightness expands from center" },
      { name: "Grain Shift", desc: "Texture density subtly changes across cut" },
      { name: "Whisper Pan", desc: "Tiny lateral drift, almost still" },
      { name: "Ghost Frame", desc: "Echo of previous frame lingers under new" },
      { name: "Diffusion Pull", desc: "Soft fog/haze layer dissolves revealing sharper image" },
      { name: "Vignette Breathe", desc: "Edge darkness expands and contracts gently" },
      { name: "Color Temp Drift", desc: "Warmer to cooler tone shifts across shot" },
      { name: "Halation Glow", desc: "Soft red bloom around highlights, vintage filmic" },
      { name: "Subtle Anamorphic Streak", desc: "Faint horizontal streak from practical light" },
      { name: "Soft Cut", desc: "1-2 frame cross-fade, near invisible cut" },
      { name: "Touch Transition", desc: "Subject touches edge of frame, swap on contact" },
      { name: "Fade-Through-Color", desc: "Brief solid color (white/black) bridges scenes" },
      { name: "Held Breath", desc: "Frozen still moment of stillness before cut" },
      { name: "Quiet Reveal", desc: "Subject simply enters frame, no fanfare" },
      { name: "Wind Drift", desc: "Natural wind movement bridges static frames" },
      { name: "Light Ray Crawl", desc: "Sunbeam slowly traverses scene over time" },
      { name: "Reflection Catch", desc: "Brief reflection in window/water bridges cut" },
      { name: "Backlight Glow", desc: "Rim light strengthens through transition" },
      { name: "Edge Bloom", desc: "Frame edges softly bloom inward" },
      { name: "Spec Highlight Pop", desc: "Brief specular highlight catches cut moment" },
      { name: "Atmospheric Haze Pull", desc: "Haze clears revealing detail beneath" },
      { name: "Soft Iris Open", desc: "Aperture opens gently, depth shifts" },
      { name: "Held Stillness", desc: "Extended stillness with subtle ambient motion" }
    ],
    mood: [
      { name: "Dreamcore", desc: "Surreal hyper-saturated nostalgic, uncanny familiar" },
      { name: "Dystopian", desc: "Decay, muted palette, broken tech, oppressive mood" },
      { name: "Altered State", desc: "Warped reality, distortion of perception, hallucinatory" },
      { name: "Anthropo", desc: "Vật vô tri trở nên ấm áp như có hồn, friendly objects" },
      { name: "BTS Raw", desc: "Behind-the-scenes feel, unpolished documentary energy" },
      { name: "Vintage Film", desc: "16mm grain, halation, warm fade, organic imperfection" },
      { name: "VHS / Found Footage", desc: "Tracking artifacts, scan lines, raw discovered tape", source: "eyecannndy.com/technique/vhs" },
      { name: "Liminal", desc: "Empty in-between spaces, eerie absence, hallways at night" },
      { name: "Nostalgic", desc: "Polaroid soft fade, faded color, memory-warm" },
      { name: "Surreal Dali", desc: "Impossible logic, melting forms, dream symbolism" },
      { name: "Brutalist", desc: "Concrete heavy, hard geometric lines, monumental" },
      { name: "Cyberpunk", desc: "Neon, rain, glow, dense urban future" },
      { name: "Solar / Sun-Drenched", desc: "Sun-blasted overexposed, warm grade, optimistic" },
      { name: "Glitch Aesthetic", desc: "Digital decay, datamosh, broken signal beauty" },
      { name: "Cottagecore", desc: "Pastoral soft warm, hand-made textures, slow nature" },
      { name: "Ironman / MCU Tech-HUD", desc: "Holographic UI overlays, blue/orange tech accents, scan-line interface" },
      { name: "Blade Runner Noir", desc: "Neon rain, smoky atmospheric, lonely future city" },
      { name: "Dune Villeneuve", desc: "Sand-blasted warm tones, monolithic scale, vast emptiness" },
      { name: "A24 Naturalism", desc: "Soft daylight, intimate composition, restrained pacing" },
      { name: "Wes Anderson", desc: "Perfect central symmetry, pastel palette, deadpan whimsy" },
      { name: "Nolan IMAX", desc: "Massive scale, practical realism, weighty grandeur" },
      { name: "Wong Kar-wai", desc: "Slow-motion melancholy, neon corridor, lonely longing" },
      { name: "Tarkovsky Long-Take", desc: "Long take meditative, water/fire elements, spiritual" },
      { name: "Kubrick One-Point", desc: "One-point perspective, symmetrical corridor, unsettling calm" },
      { name: "Coen Brothers", desc: "Wide cold landscapes, deadpan absurdity, fated tone" },
      { name: "Spielberg Wonder", desc: "Low-angle awe shot, child gazing up at majesty" },
      { name: "Fincher Precise", desc: "Locked frame, surgical precision, cold technical control" },
      { name: "Lynch Dream Logic", desc: "Slow surreal, red curtains, unease, dream geography" },
      { name: "Refn Neon", desc: "Synthwave neon, slow zoom, stylized violence-as-art" },
      { name: "Edgar Wright Kinetic", desc: "Kinetic cuts, exact sound sync, whip-pan comedy timing" },
      { name: "Tony Scott Saturated", desc: "Heavy color grade, smoke, sun bursts, motion blur action" },
      { name: "Mann Heat Urban", desc: "Street neon, isolated figures, hyper-real night city" },
      { name: "Apocalypse Now Heat", desc: "Heat haze, fire, slow zoom into chaos" },
      { name: "Mad Max Fury", desc: "Orange/teal extreme grade, kinetic chase chaos" },
      { name: "Akira Cyber-Anime", desc: "Anime cyber-tech speed lines, neon Tokyo motion" },
      { name: "Pixar Charm", desc: "Warm lighting, character-focused, emotional accessibility" },
      { name: "Studio Ghibli", desc: "Soft wind, natural elements, gentle painted realism" },
      { name: "Marvel Action", desc: "Lens flares, fast camera punch, hero shot grandeur" },
      { name: "John Wick Clean", desc: "Clean fight choreography, neon noir, precise action" },
      { name: "Tarantino Pulp", desc: "Saturated retro, trunk shot, stylized dialogue close-up" }
    ]
  };
