-- Eventus AI Lab content table reset.
-- Run this in Supabase SQL Editor when you do not need to keep old content data.

drop table if exists public.wiki_pages cascade;
drop table if exists public.lab_pages cascade;

create table public.lab_pages (
  id bigint generated by default as identity primary key,
  category text not null,
  title text not null,
  content text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint lab_pages_category_title_unique unique (category, title)
);

alter table public.lab_pages enable row level security;

create policy "Allow public read lab pages"
  on public.lab_pages
  for select
  to anon, authenticated
  using (true);

create policy "Allow public insert lab pages"
  on public.lab_pages
  for insert
  to anon, authenticated
  with check (true);

create policy "Allow public update lab pages"
  on public.lab_pages
  for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "Allow public delete lab pages"
  on public.lab_pages
  for delete
  to anon, authenticated
  using (true);

grant select, insert, update, delete on table public.lab_pages to anon, authenticated;
grant usage, select, update on sequence public.lab_pages_id_seq to anon, authenticated;
